apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitalbank2
  labels:
    app: digitalbank
spec:
  replicas: 15
  selector:
    matchLabels:
      app: digitalbank
  template:
    metadata:
      labels:
        app: digitalbank
    spec:
      containers:
      - name: my-digitalbank
        image: nmsudhanan75/digitalbank2
        ports:
        - containerPort: 80
